name: Update prod cache of build materials

on:
  workflow_dispatch: {}

env:
  PROJECT: prod-images-c6e5
  FQ_SERVICE_ACCOUNT: prod-images-ci@prod-images-c6e5.iam.gserviceaccount.com
  SOURCE_CACHE_BUCKET: wolfi-sources

jobs:
  update-cache:
    runs-on: ubuntu-latest
    if: github.repository == 'wolfi-dev/os'

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - uses: chainguard-dev/actions/setup-melange@main

    - uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: "projects/618116202522/locations/global/workloadIdentityPools/prod-shared-e350/providers/prod-shared-gha"
        service_account: ${{env.FQ_SERVICE_ACCOUNT}}

    - uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{env.PROJECT}}

    - name: 'Update cache of build materials for all packages'
      run: |
        for cfg in $(ls -1 | grep '.*\.yaml'); do
          echo "Updating cache for ${cfg}...";
          melange update-cache --cache-dir gs://${{env.SOURCE_CACHE_BUCKET}}/ "${cfg}" || true;
        done
